"""empty message

Revision ID: 34399e53aa67
Revises: 38a976fcb9f7
Create Date: 2020-09-01 21:20:25.366623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34399e53aa67'
down_revision = '38a976fcb9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Movie', 'release_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movie', sa.Column('release_date', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
