"""empty message

Revision ID: 35df127457f1
Revises: 8b81c4514813
Create Date: 2020-09-01 22:38:12.842765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35df127457f1'
down_revision = '8b81c4514813'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Actor', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
