"""empty message

Revision ID: 38a976fcb9f7
Revises: 
Create Date: 2020-08-31 20:11:44.109139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a976fcb9f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('Actor', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Actor', 'gender')
    op.drop_column('Actor', 'age')
    # ### end Alembic commands ###
