"""empty message

Revision ID: 3ae894139f6f
Revises: 35df127457f1
Create Date: 2020-09-01 22:38:39.104545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae894139f6f'
down_revision = '35df127457f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Actor', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Actor', 'gender')
    # ### end Alembic commands ###
