"""empty message

Revision ID: 8b81c4514813
Revises: 34399e53aa67
Create Date: 2020-09-01 21:21:20.582347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b81c4514813'
down_revision = '34399e53aa67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movie', sa.Column('release_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Movie', 'release_date')
    # ### end Alembic commands ###
