"""empty message

Revision ID: 94ce59843907
Revises: 3ae894139f6f
Create Date: 2020-09-01 22:39:46.756665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ce59843907'
down_revision = '3ae894139f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Cast_movie_id_fkey', 'Cast', type_='foreignkey')
    op.drop_column('Cast', 'movie_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cast', sa.Column('movie_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('Cast_movie_id_fkey', 'Cast', 'Movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###
