"""empty message

Revision ID: e097dd61c932
Revises: 94ce59843907
Create Date: 2020-09-01 22:40:11.107663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e097dd61c932'
down_revision = '94ce59843907'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cast', sa.Column('movie_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Cast', 'Movie', ['movie_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Cast', type_='foreignkey')
    op.drop_column('Cast', 'movie_id')
    # ### end Alembic commands ###
